name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install dependencies
      run: lein deps
      run: npm install -y
    - name: Run Clojure tests
      run: lein test
    - name: Run ClojureScript tests
      run: npm run test
